### ISSUE TITLE
2.3.4.1 Not On Packagist

### ISSUE THREAD

**Issue by sprankhub** [yireo/magento2-replace-core#11]
The version 2.3.4.1 is not available on packagist. IIRC, Composer / Packagist does not support such a version number. I think it needs to be called e.g. 2.3.4-p1. Could you please check and fix?

**Comment by jissereitsma** [comment]
This is such a pita. On request from others, I have introduced this new release versioning, but indeed 2.3.4.1 does not seem to work. I have now switched to `2.3.4-p1`. Or actually, the following release has been made as a test https://github.com/yireo/magento2-replace-core/releases/tag/2.3.1-p1 but I'm waiting for Packagist to include this: https://packagist.org/packages/yireo/magento2-replace-core

**Comment by jissereitsma** [comment]
The `pita` suffix works and is available now.

**Comment by sprankhub** [comment]
Sorry, @jissereitsma ¯\\_(ツ)_/¯ Thanks anyway!
