### ISSUE TITLE
2.4.5, can't replace Adobe Ims due to hard-coupled TwoFactorAuth

### ISSUE THREAD

**Issue by peterjaap** [yireo/magento2-replace-core#14]
See https://github.com/magento/magento2/issues/35962

**Comment by jissereitsma** [comment]
Actually, because of this, TWA is also removed here: https://github.com/yireo/magento2-replace-core/blob/magento-2.4/composer.json#L70 :(

**Comment by peterjaap** [comment]
Meh that's a less than satisfactory workaround, but at least the stores using this will build now. Personally I would've gone for the option to remove the `adobe-ims` extensions (see my Additional Information section [here](https://github.com/magento/magento2/issues/35962)).

We have to keep an eye on https://github.com/magento/magento2/issues/35962 - as soon as it's fixed, we can remove the TFA module from the replace list again.

**Comment by henkvalk** [comment]
I'm at 2.4.6-p3 and I need to replace `magento/module-admin-adobe-ims-two-factor-auth` to make it work.
