### ISSUE TITLE
Checkout session flushed When Magento_Persistent is not enabled

### ISSUE THREAD

**Issue by edwinljacobs** [yireo/magento2-replace-core#2]
Hello this is just for information purposes:

https://github.com/magento/magento2/issues/21614
Since Magento_Persistent is disabled in this package I thought it would be good to add a reference to this issue.

You could decide to remove the Magento_Persistent entry from the composer json but this is up to you.

**Comment by edwinljacobs** [comment]
This is fixed in Magento 2.3.3

**Comment by nocturnalfrog** [comment]
@edwinljacobs, how about the 2.2 branch?
Will the fix be backported?
